language: ruby
sudo: false
rvm:
- 2.1

#before_script:
# - chmod +x ./script/cibuild # or do this locally and commit
install:
  - gem install jekyll
  - gem install html-proofer jemoji jekyll-sitemap jekyll-mentions jekyll-paginate jekyll-redirect-from
  - gem install pygments.rb
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
#script: ./script/cibuild
script:
  - jekyll build
#  - htmlproof ./_site
notifications:
  slack:
    rooms:
      - africa-arabia-roc:RtLMfiuARuPNXMNIXn5RVTkF#code
