# YAML metadata of the jobs in the jenkins build system.
# this can be obtained via the REST interface as well.
---
# First, the compilers
- name: GMP
  description: GNU Multiprecision library
  job: gmp-deploy
  versions: {5.1.3}
  tags: {"compilers", "cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/gmp-deploy

- name: MPFR
  description: GNU MPFR is a C library for multiple-precision floating-point computations with correct rounding.
  job: mpfr-deploy
  versions: {3.1.2}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/mpfr-deploy

- name: MPC
  description: Gnu MPC is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
  job: mpc-deploy
  versions: {1.0.1}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/mpc-deploy

- name: GCC
  description: 'The GNU Compiler Collection'
  job: 'gcc-deploy'
  versions: {"4.8.2", "4.8.4", "4.9.2", "4.7.2", "5.1.0"}
  tags: {"compilers","cvmfs"}
  repo: 'https://github.com/SouthAfricaDigitalScience/gcc-deploy'

- name: CMake
  description: Cross-platform build tools
  job: cmake-deploy
  versions: {3.1.0}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/cmake-deploy
# Then the libraries

- name: BOOST C++
  description: Boost provides free peer-reviewed portable C++ source libraries.
  job: boost-deploy
  versions: {1.57.0, 1.56.0, 1.55.0}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/boost-deploy

- name: Python
  description: Python is a programming language that lets you work quickly and integrate systems more effectively.
  job: python-deploy
  versions: {2.6.9,3.4.1}
  tags: {"frameworks"}
  repo: https://github.com/SouthAfricaDigitalScience/python-deploy

- name: LAPACK
  description: Linear Algorithm packages for HPC
  job: lapack-deploy
  versions: {3.5.0}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/lapack-deploy

- name: GSL
  description: GNU Science Libraries
  job: gsl-deploy
  versions: {1.16,1.15,1.14}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/gsl-deploy


- name: HDF5
  description: HDF5 is a data model, library, and file format for storing and managing data.
  job: hdf5-deploy
  versions: {1.8.14}
  tags: {"libraries"}
  repo: https://github.com/SouthAfricaDigitalScience/hdf5-deploy

- name: FFTW3
  description: FFTW is a C subroutine library for computing the discrete Fourier transform (DFT) in one or more dimensions, of arbitrary input size, and of both real and complex data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or DCT/DST).
  job: fftw3-deploy
  versions: {3.3.4}
  tags: {"libraries","cvmfs"}
  repo: fftw3-deploy

#### Chemistry

- name: Quantum Espresso
  description: "Quantum ESPRESSO is an integrated suite of Open-Source computer codes for electronic-structure calculations and materials modeling at the nanoscale. It is based on density-functional theory, plane waves, and pseudopotentials."
  job: quantum-espresso-deploy
  versions: {5.1.3}
  tags: {"chemistry"}
  repo: quantum-espresso-deploy


- name: SciPy
  description:
  job:
  versions:
  tag:
  repo:

- name: NumPy
  description:
  job:
  versions:
  tag:
  repo:

- name: MatPlotLib
  description:
  job:
  versions:
  tag:
  repo:

- name: Pandas
  description:
  job:
  versions:
  tag:
  repo:

- name: SymPy
  description:
  job:
  versions:
  tag:
  repo:

- name:
  description:
  job:
  versions:
  tag:
  repo:

- name:
  description:
  job:
  versions:
  tags:
  repo:


- name: GADGET
  description:
  job:
  versions:
  tags:
  repo:


- name:
  description:
  job:
  versions:
  tag:
  repo:


#### proposed/requested

- name: Fluent
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: OpenFoam
  description:
  job:
  versions: {2.1.1}
  tags: {"requested"}
  repo:

- name: Dlpoly
  description:
  job:
  versions: 4.3
  tags: {"requested"}
  repo:

- name: GROMACS
  description:
  job:
  versions: {4.6.1}
  tags: {"requested"}
  repo:

- name: Cosmo MC
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: Gaussian
  description:
  job:
  versions: {G09}
  tags: {"reqeusted"}
  repo:



- name: WRF
  description:
  job:
  versions: {3.3,3.5}
  tags: {"requested"}
  repo:

- name: Ferret
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: Amber
  description:
  job:
  versions: {12}
  tags: {"requested"}
  repo:

- name: Vasp
  description:
  job:
  versions: {5.2}
  tags: {"requested"}
  repo:

- name: Velvet
  description:
  job:
  versions: {1.0.19}
  tags: {"requested"}
  repo:

- name: Emboss
  description:
  job:
  versions: {6.2}
  tags: {"requested"}
  repo:

  - name: Plink
    description: "PLINK is a free, open-source whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner."
    job: plink-deploy
    versions: 1.9
    tags: {"requested"}
    repo:
