# YAML metadata of the jobs in the jenkins build system.
# this can be obtained via the REST interface as well.
---
- name: zlib
  description: Free Compression Library
  job: zlib-deploy
  versions: {1.2.8}
  tags: {"libraries"}
  repo: https://github.com/SouthAfricaDigitalScience/zlib-deploy
# First, the compilers
- name: GMP
  description: GNU Multiprecision library
  job: gmp-deploy
  versions: {5.1.3}
  tags: {"compilers", "cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/gmp-deploy

- name: MPFR
  description: GNU MPFR is a C library for multiple-precision floating-point computations with correct rounding.
  job: mpfr-deploy
  versions: {3.1.2}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/mpfr-deploy

- name: MPC
  description: Gnu MPC is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result
  job: mpc-deploy
  versions: {1.0.1}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/mpc-deploy

- name: GCC
  description: 'The GNU Compiler Collection'
  job: 'gcc-deploy'
  versions: {"4.9.2","5.1.0","5.2.0"}
  tags: {"compilers","cvmfs"}
  repo: 'https://github.com/SouthAfricaDigitalScience/gcc-deploy'

- name: CMake
  description: Cross-platform build tools
  job: cmake-deploy
  versions: {3.4.0}
  tags: {"compilers","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/cmake-deploy

- name: LLVM
  description: "The LLVM Project is a collection of modular and reusable compiler and toolchain technologies."
  job: llvm-deploy
  versions: {3.6.2}
  tags: {"compilers","dev"}
  repo: https://github.com/SouthAfricaDigitalScience/llvm-deploy


# Then the libraries

- name: ncurses
  description: The Ncurses library is a free software emulation of curses in System V Release 4.0, and more.
  job: ncurses-deploy
  versions: {5.9}
  tags: {"libraries"}
  repo: https://github.com/SouthAfricaDigialScience/ncurses-deploy

- name: BOOST C++
  description: Boost provides free peer-reviewed portable C++ source libraries.
  job: boost-deploy
  versions: {1.57.0, 1.56.0, 1.55.0}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/boost-deploy

- name: Python
  description: "Python is a programming language that lets you work quickly and integrate systems more effectively."
  job: python-deploy
  versions: {2.6.9,3.4.1}
  tags: {"python"}
  repo: https://github.com/SouthAfricaDigitalScience/python-deploy

- name: LAPACK
  description: Linear Algorithm packages for HPC
  job: lapack-deploy
  versions: {3.5.0}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/lapack-deploy

- name: ScaLAPACK
  description: Scalable, parallel Linear Algebra Libraries
  job: scalapack-deploy
  versions: {2.2.0}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/scalapack-deploy

- name: ATLAS
  description: Automatically-Tuned Linear Algebra Software
  job: atlas-deploy
  versions: {3.10.2}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/atlas-deploy

- name: GSL
  description: GNU Science Libraries
  job: gsl-deploy
  versions: {1.16,2.0,2.1 }
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/gsl-deploy


- name: HDF5
  description: HDF5 is a data model, library, and file format for storing and managing data.
  job: hdf5-deploy
  versions: {1.8.14,1.8.15}
  tags: {"libraries","dev"}
  repo: https://github.com/SouthAfricaDigitalScience/hdf5-deploy

- name: NetCDF
  description: "NetCDF (network Common Data Form) is a set of software libraries
and machine-independent data formats that support the creation, access, and sharing of array-oriented scientific data."
  job: netcdf-deploy
  tags: {"libraries","dev"}
  versions: {}

- name: FFTW3
  description: FFTW is a C subroutine library for computing the discrete Fourier transform (DFT) in one or more dimensions, of arbitrary input size, and of both real and complex data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or DCT/DST).
  job: fftw3-deploy
  versions: {3.3.4}
  tags: {"libraries","cvmfs"}
  repo: https://github.com/SouthAfricaDigitalScience/fftw3-deploy

- name: SparseHash
  description: Google's SparseHash library
  job: sparsehash-deploy
  versions: 2.0.3
  tags: {"libraries"}
  repo: https://github.com/SouthAfricaDigialScience/sparsehash-deploy

##### Language #####

- name: HTK
  description:  Hidden Markov Model Toolkit (HTK)
  job: htk-deploy
  versions: 3.5.beta-1
  tags: {"language","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/htk-deploy

#### Chemistry

- name: Quantum Espresso
  description: "Quantum ESPRESSO is an integrated suite of Open-Source computer codes for electronic-structure calculations and materials modeling at the nanoscale. It is based on density-functional theory, plane waves, and pseudopotentials."
  job: quantum-espresso-deploy
  versions: {5.1.3}
  tags: {"chemistry","dev"}
  repo: quantum-espresso-deploy

- name: Abinit
  description: "ABINIT is a package whose main program allows one to find the total energy, charge density and electronic structure of systems made of electrons and nuclei (molecules and periodic solids) within Density Functional Theory (DFT), using pseudopotentials and a planewave or wavelet basis."
  job: abinit-deploy
  versions: 7.10.5
  tags: {"chemistry","dev"}
  repo: https://github.com/SouthAfricaDigialScience/abinit-deploy

### bioinformatics ###

- name: Velvet
  description: Sequence assembler for very short reads
  job: velvet-deploy
  versions: {1.2.10}
  tags: {"bioinformatics","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/velvet-deploy

- name: OASES
  description: De novo transcriptome assembler for very short reads
  job: oases-deploy
  versions: {0.2.08}
  tags: {"bioinformatics","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/oases-deploy


# H3A stuff
- name: FastQC
  description: A quality control application for high throughput sequence data
  job:
  versions: 0.11.4
  tags: {"Requested","H3ABioNet"}
  repo:

- name: PRINSEQ
  description: PReprocessing and INformation of SEQuence data
  job:
  versions: {0.20.4}
  tags: {"Requested","H3ABioNet"}
  repo:


- name: SolexaQA
  description: SolexaQA calculates sequence quality statistics and creates visual representations of data quality for second-generation sequencing data
  job:
  versions: {3.1.4}
  tags: {"Requested","H3ABioNet"}
  repo:

- name: Trimmomatic
  description: A flexible read trimming tool for Illumina NGS data
  job:
  versions: {0.35}
  tags: {"Requested","H3ABioNet"}
  repo:

### Python stuff ###

- name: SciPy
  description: Scientific Python
  job: scipy-deploy
  versions: {0.5.1}
  tags: {"python"}
  repo: https://github.com/SouthAfricaDigialScience/scipy-deploy

- name: NumPy
  description: "Numerical Python"
  job: numpy-deploy
  versions: {1.9.1}
  tags: {python","cvmfs","dev"}
  repo: https://github.com/SouthAfricaDigialScience/numpy-deploy

- name: MatPlotLib
  description: "Plotting functions for python"
  job: matplotlib-deploy
  versions: {4.8.4,4.9.2}
  tags: {"libraries","python","dev"}
  repo: https://github.com/SouthAfricaDigialScience/matplotlib-deploy

- name: Pandas
  description: "pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming"
  job: pandas-deploy
  versions: {0.17.0}
  tags: {"libraries","python","dev"}
  repo: https://github.com/SouthAfricaDigitalScience/pandas-deploy

- name: SymPy
  description: "Symbolic Python"
  job: sympy-deploy
  versions: {0.7.6.1}
  tags: {"dev","python","frameworks"}
  repo: https://github.com/SouthAfricaDigitalScience/Sympy-deploy

- name: Repast HPC
  description: "Parallel Agent-based modelling"
  job: repast-hpc-deploy
  versions: 2.1
  tags: {"dev","frameworks"}
  repo: https://github.com/SouthAfricaDigialScience/repast-hpc-deploy

- name:
  description:
  job:
  versions:
  tags:
  repo:


### Astro ####

- name: HEAsoft
  description: "A Unified Release of the FTOOLS and XANADU Software Packages"
  job: heasoft-deploy
  versions: {6.17}
  tags: {"astronomy","frameworks"}
  repo: https://github.com/SouthAfricaDigialScience/heasoft-deploy

- name: CFITSIO
  description: "The C-implementation of the FITS I/O library"
  job: fitsio-deploy
  versions: 33.70
  tags: {"astronomy","cvmfs"}
  repo: https://github.com/SouthAfricaDigialScience/fitsio-deploy


- name: GADGET
  description:
  job:
  versions:
  tags:
  repo:


- name:
  description:
  job:
  versions:
  tags:
  repo:


#### proposed/requested

- name: Fluent
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: OpenFoam
  description:
  job:
  versions: {2.1.1}
  tags: {"requested"}
  repo:

- name: Dlpoly
  description:
  job:
  versions: 4.3
  tags: {"requested"}
  repo:

- name: GROMACS
  description:
  job: gaussian-deploy
  versions: {4.6.1}
  tags: {"requested"}
  repo: https://github.com/SouthAfricaDigialScience/gromacs-deploy

- name: Cosmo MC
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: Gaussian
  description:
  job:
  versions: {G09}
  tags: {"reqeusted"}
  repo:



- name: WRF
  description:
  job:
  versions: {3.3,3.5}
  tags: {"requested"}
  repo:

- name: Ferret
  description:
  job:
  versions:
  tags: {"requested"}
  repo:

- name: Amber
  description:
  job:
  versions: {12}
  tags: {"requested"}
  repo:

- name: Vasp
  description:
  job:
  versions: {5.2}
  tags: {"requested"}
  repo:

- name: Emboss
  description:
  job:
  versions: {6.2}
  tags: {"requested"}
  repo:

  - name: Plink
    description: "PLINK is a free, open-source whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner."
    job: plink-deploy
    versions: 1.9
    tags: {"requested"}
    repo:
