- name: Applications
  title: Applications
  url: applications
  icon: rocket
  external: false
  service_list: []

- name: Infrastructure
  title: ROC Interoperability services
  url: core
  icon: sitemap
  external: false
  service_list:
    - name: SAM-NAGIOS
      url: http://nagios.c4.csir.co.za
      roc_service: true
      middleware: UMD
      release_version: 2
      gris_service: true
    - name: Top-BDII
      title: Top-level information index - tells you who's got what and how much.
      middleware: UMD
      release_version: 3
      grid_service: true
      url: https://nagios.c4.csir.co.za/
    - name: Accounting
      title: Central Accounting service
      url: http://accounting.egi.eu/
      external: true
      roc_service: true

- name: Security
  title: CSIRT and SecOps
  url: security
  icon: key
  service_list: []

- name: Compute &amp; Data
  title: HPC, Grid and Cloud services
  url: grid
  icon: server
  external: false
  service_list:
    - name: Compute
      title: HPC, Grid and Cloud computing services
      url: compute
      external: false
    - name: Data
      title: Data Storage, Discovery, Movement and Management Services
      url: data
      external: false
    - name: UI
      title: User Interface
      middleware: UMD
      release_version: 3
      grid_service: true
      url: https://nagios.c4.csir.co.za/
    - name: LFC
      title: Logical File Catalogue - find and manage your data
      middleware: UMD
      release_version: 3
      grid_service: true
      url: https://nagios.c4.csir.co.za/
    - name: Workload Management Server
      title: Workload Management Service - metascheduler for the grid
      middleware: UMD3
      release_version: 3
      grid_service: true
      url: https://nagios.c4.csir.co.za/

- name: Science
  title: Science Gateways and Services for Open Science
  url: science
  external: true
  roc_service: true
  icon: flask
  service_list:

- name: Identity
  title: Identity Management and Federation Services
  url: identity
  icon: certificate
  external: false
  service_list:
  - name: Identity Management
    title: Perun Identity Management Service
    url: perun
    external: false
  - name: Identity Federation
    title: Federated Identity Services
    url: idf
    external: false

- name: Support
  title: Technical Support and Training
  url: support
  external: false
  icon: support
  service_list:
  - name: Technical Support
    title: GGUS
    url: https://ggus.eu
    external: true


- name: Dev &amp; CI
  title: Continuous Development, Integration and Delivery
  url: code-rade/
  status: ok
  external: false
  roc_service: true
  icon: wrench
