- name: Compute Services
  title: HPC, Grid and Cloud computing services
  url: compute
  external: false

- name: Data Services
  title: Data Storage, Discovery, Movement and Management Services
  url: data
  external: false

- name: Science Gateway
  title: AfricaGrid Science Gateway
  url: https://sgw.africa-grid.org
  external: true

- name: Identity Management
  title: Perun Identity Management Service
  url: perun
  external: false

- name: Identity Federation
  title: Federated Identity Services
  url: idf
  external: false

- name: Technical Support
  title: GGUS
  url: https://ggus.eu
  external: true
